version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - user-service
      - course-service
      - payment-service
    environment:
      - JWT_SECRET=secret_key

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb

  course-service:
    build: ./course-service
    container_name: course-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/coursedb

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/paymentdb

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"

  frontend-react:
    build: ./frontend-react
    container_name: frontend
    ports:
      - "3005:3000"
    depends_on:
      - api-gateway

volumes:
  mongo_data:
