# Étape 1 : builder l'app
FROM node:18-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances en premier
COPY package.json ./
RUN npm install

# Copier le reste du code
COPY . .

# Build de l’application
RUN npm run build

# Étape 2 : servir les fichiers avec Nginx
FROM nginx:stable-alpine

# Copier les fichiers de build générés vers l'emplacement par défaut de Nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
